# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac3f1e9ce49349d4ba120412b42d4012dd9b06a25e884f697a4148a3b9e3c737a86b28f2a356bd448a7a9c6c92dffd26c277b6ab7ac3e0ba08205d0c0b0a865c

test:
  secret_key_base: 0ba85fd1c270fe7ada2c3c2723fe585e0e9ae93554ffddbc48551728cb347705ca2c149271f047a1b85eb155a1e1ee54389f05d7940e194461f61f347282423f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
